### PR TITLE
fix(delayWhen): correctly handle synchronous duration observable

### LINKED ISSUE #2587: Bug: delayWhen operator returns an Observable that does not complete.
**RxJS version:**
5.3.0

**Code to reproduce:**
```
Rx.Observable.of('foo')
  .delayWhen(function() {
    return Rx.Observable.of('bar');
  })
  .subscribe({
    next: function(x) {
      console.log('next');
    },
    complete: function() {
      console.log('complete');
    }
  });
```

**Expected behavior:**
Output
`'next'`
`'complete'`

**Actual behavior:**
Output
`'next'`

**Additional information:**
If you substitute `delayWhen(...)` for say `delay(1000)` in the above, it will emit complete as expected.

[Here is a jsFiddle](https://jsfiddle.net/b8sd30k3/) using [https://unpkg.com/rxjs/bundles/Rx.min.js](https://unpkg.com/rxjs/bundles/Rx.min.js) showcasing the issue.

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR fixes outersubscriber behavior of delayWhen operator, to complete it correctly when duration selector returns synchronous observable. Similar to https://github.com/ReactiveX/rxjs/pull/1490 in crux.

**Related issue (if exists):**
- closes #2587

### CODE REVIEW

**Comment by kwonoj** [comment]
This shouldn't cause any breaking changes.

File: src/operator/delayWhen.ts [hunk 1]
```diff
@@ -56,7 +56,7 @@ export function delayWhen<T>(this: Observable<T>, delayDurationSelector: (value:
                              subscriptionDelay?: Observable<any>): Observable<T> {
   if (subscriptionDelay) {
     return new SubscriptionDelayObservable(this, subscriptionDelay)
-            .lift(new DelayWhenOperator(delayDurationSelector));
```
Comment (benlesh) [inline src/operator/delayWhen.ts]: In the future, these sorts of formatting corrections should be in a separate commit for easier review.

File: src/operator/delayWhen.ts [hunk 2]
```diff
@@ -112,7 +112,7 @@ class DelayWhenSubscriber<T, R> extends OuterSubscriber<T, R> {
         this.tryDelay(delayNotifier, value);
       }
     } catch (err) {
-        this.destination.error(err);
```
Comment (benlesh) [inline src/operator/delayWhen.ts]: same as above.
