### PR TITLE
fix(never): Observable.never() Observable.empty() .ignoreElements () now return Observable<never>

### LINKED ISSUE #2640: Return type of .ignoreElements() and .empty() should be Observable<never>
**RxJS version:** 5.4.0

**Code to reproduce:**
```ts
/** Returns an Observable of files */
function fetchFiles(): Observable<string> {
  return Observable.of('foo', 'bar', 'baz')
}

const files = new Set<string>()

/** Returns an Observable that emits no items and completes when the task is done */
function updateFiles() {
  return fetchFiles()
    .do(file => {
      files.add(file)
    })
    .ignoreElements()
}
```

**Expected behavior:**
Inferred return type of `updateFiles` should be `Observable<never>`. The Observable never emits items, so the items don't have a type, similar to how a function that always throws has no return type - it `never` emits/returns.

**Actual behavior:**
Emitted return type is `Observable<string>`

### PR DESCRIPTION
**Pull request by jayphelps**
fixes #2640

BREAKING CHANGE: Previously, `Observable.never()` `Observable.empty()`
and the `.ignoreElements()` operator all returned `Observable<T>` which
was incorrect since they actually never emit anything. Now they all
return `Observable<never>` (`never` was added in TS 2.0 as a special
type)

### CODE REVIEW

File: src/observable/EmptyObservable.ts [hunk 1]
```diff
@@ -57,11 +57,11 @@ export class EmptyObservable<T> extends Observable<T> {
...
    * @owner Observable
    */
-  static create<T>(scheduler?: IScheduler): Observable<T> {
-    return new EmptyObservable<T>(scheduler);
+  static create(scheduler?: IScheduler): Observable<never> {
+    return new EmptyObservable(scheduler);
   }
 
-  static dispatch<T>(arg: DispatchArg<T>) {
+  static dispatch(arg: DispatchArg<never>) {
```
Comment (kwonoj) [inline src/observable/EmptyObservable.ts]: wouldn't it better to make `DispatchArg` as non-generic in line 6? (also making this fn to private and not export dispatcharg would be preferred)

Comment (jayphelps) [inline src/observable/EmptyObservable.ts]: wasn't clear if DispatchArg was used elsewhere since it was exported, but certainly can 👍

Comment (jayphelps) [inline src/observable/EmptyObservable.ts]: it will basically just mean I make `subscriber: Subscriber<never>` instead of `subscriber: Subscriber<T>`

**Comment by david-driscoll** [comment]
You should probably target the `next` branch instead of `master`.

**Comment by kwonoj** [comment]
(I've changed base to `next`)

**Comment by kwonoj** [comment]
ah, change itself LGTM

**Comment by jayphelps** [comment]
@kwonoj issue is that next doesn't have everything from master yet, so my branch is bringing them along for the ride. I can prolly reset my branch to the same as `next` then cherry pick my commit in, but, or next can be updated to the latest master before this is merged. LMK what ya'll would like

**Comment by jayphelps** [comment]
@kwonoj reset to `next` then cherry picked commit into it.

**Comment by jayphelps** [comment]
Need anything else for merge?
