### PR TITLE
fix(Subscription): fold ChildSubscription logic into Subscriber to prevent operators from leaking ChildSubscriptions.

### LINKED ISSUE #2244: Memory Leak with Queue Scheduler and Subject
**RxJS version:** 5.0.2

**Code to reproduce:**
Observing a subject using the `queue` scheduler creates many `QueueAction`s that are never freed.

Plnkr demonstrating issue: https://plnkr.co/edit/BBkHlpIf6MiP2eOPdIlz

Minimal code to reproduce:
```ts
import 'rxjs/add/operator/observeOn';
import { interval } from 'rxjs/observable/interval';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { queue } from 'rxjs/scheduler/queue';

const source$ = new BehaviorSubject(0);

source$.observeOn(queue).subscribe();

interval(50).subscribe(source$);
```

Create two heap allocation snapshots about 20 seconds apart and use the comparison tools to see the allocation delta. Example:

Heap Allocation Snapshot Example

**Expected behavior:**
No memory leak of previous values.

**Actual behavior:**
Previous values are retained in `QueueAction`s

### LINKED ISSUE #2355: ChildSubscriptions unsubscribed but not removed.
In the <code>switch()</code> operator, you'll find this code used to add
subscriptions to the <code>Subscriptions._subscriptions[]</code> array:

    this.add(this.innerSubscription = subscribeToResult(this, value));

And you'll find this code to remove them:

    const innerSubscription = this.innerSubscription;
    if (innerSubscription) {
      innerSubscription.unsubscribe();
      this.remove(innerSubscription);
    }

But note behavior of Subscription.add(s) is not "add s to the array and return s"; 
behavior is "create a new ChildSubscription from s, add the ChildSubscription to the array,
and return the ChildSubscription."
The consequence?  The remove() does not match the add().  The remove() becomes a silent no-op.  
The unsubscribe() was successful (good - we get correct program behavior)
but the remove() fails (bad - cannot GC these silent ChildSubscriptions).

**RxJS version:**
v5.1.0

**Code to reproduce:**

    var parentTicker = Rx.Observable.interval(1000);
    var childTickers = parentTicker.map((x) => {
      return Rx.Observable.interval(100).take(2);
    });

    var switcher = childTickers.switch();
    var sub = switcher.subscribe(function(x){
            console.log('tick #' + x + ': subscriptions = ' +
              sub._subscriptions[0]._innerSub._subscriptions.length);
          });

http://jsbin.com/zotobo/edit?js,console

**Additional information:**

PRs with specs and fixes for two operators (switch(), throttle())
will follow this message.  Take a look and tell me if you agree 
that this is a legit problem and not failed understanding on my part.

( Because if you do agree, this problem also exists in many
operators.  Operators audit(), switchMap(), switchMapTo(), windowToggle(),
windowWhen() can be fixed as above, but fixing MergeMap() e.g., is going to
require stepping back and deciding if remove() responsibility should
even live in the operators, or if it should live in the Subscription class
or ChildSubscription class rolled into the unsubscribe methods. )

### PR DESCRIPTION
**Pull request by trxcllnt**
The addition of ChildSubscription to fix #2244 accidentally introduced a different memory leak. Most operators that add and remove inner Subscriptions store the inner Subscriber instance, not the value returned by Subscription#add. When they try to remove the inner Subscription manually, nothing is removed, because the ChildSubscription wrapper instance is the one added to the subscriptions list.

Fixes #2355, and supersedes the fix in #2358. Thanks again to @johncvrs for reporting this.

### CODE REVIEW

File: src/Subscription.ts [hunk 1]
```diff
@@ -66,11 +67,25 @@ export class Subscription implements ISubscription {
...
 
-    (<any> this)._subscriptions = null;
+    this.closed = true;
+    this._parent = null;
+    this._parents = null;
+    // null out _subscriptions first so any child subscriptions that attempt
+    // to remove themselves from this subscription will noop
+    this._subscriptions = null;
+
+    let index = -1, len = _parents && _parents.length || 0;
```
Comment (jayphelps) [inline src/Subscription.ts]: IMO we should prefer multiline declarations for clarity--that's just my opinion tho.

File: src/Subscription.ts [hunk 2]
```diff
@@ -66,11 +67,25 @@ export class Subscription implements ISubscription {
...
+
+    // if this._parent is null, then so is this._parents, and we
+    // don't have to remove ourselves from any parent subscriptions.
+    while (_parent) {
+      _parent.remove(this);
+      // if this._parents is null or index >= len,
+      // then _parent is set to false, and the loop exits
+      _parent = ++index < len && _parents[index];
```
Comment (jayphelps) [inline src/Subscription.ts]: I think this is harder to grok than neccesary--shouldn't need a comment that describes what it does.

File: src/Subscription.ts [hunk 3]
```diff
@@ -168,37 +189,25 @@ export class Subscription implements ISubscription {
...
 
-  _unsubscribe() {
-    const { _innerSub, _parent } = this;
-    _parent.remove(this);
-    _innerSub.unsubscribe();
+  private _addParent(parent: Subscription) {
+    let { _parent, _parents } = this;
+    if (!_parent) {
+      this._parent = parent;
+    } else if (_parents || (_parents = this._parents = [])) {
```
Comment (jayphelps) [inline src/Subscription.ts]: Can we move this assignment out of the conditional and into the block instead?

**Comment by blesh** [comment]
Pending @jayphelps' requests, it LGTM

File: src/Subscription.ts (hunk 3 above)
Comment (jayphelps) [inline src/Subscription.ts]: Something like
```js
 } else {
  if (!_parents) {
    _parents = this._parents = [];
  }
  _parents.push(this);
 }
```

I get that these checks are annoying, perhaps there's a better place to set defaults.

**Comment by blesh** [comment]
The coveralls change looks like unfortunate math. This fix is too critical to block over a 0.01% coverage change. I'm going to go ahead and merge.
