### PR TITLE
Bring back Iterable<T> and Iterator<T> interfaces

### LINKED ISSUE #2306: Observable.from(iterable) generates Typescript compiler error
**RxJS version:** 5.0.3

**Code to reproduce:**
```
function* generateDoubles(seed: number) {
  let i = seed;
  while (true) {
    yield i;
    i = 2 * i; // double it
  }
}

const iterator = generateDoubles(3);
const result = Rx.Observable.from<number>(iterator).take(10);
result.subscribe((x: number) => console.log(x));
```

**Expected behavior:**
Since this is the example given on  [reactivex.io](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-from)
It would be expected to compile in Typescript without an error.

**Actual behavior:**
```
error TS2345: Argument of type 'IterableIterator<number>' is not assignable to parameter of type 'ObservableInput<number>'.
  Type 'IterableIterator<number>' is not assignable to type 'PromiseLike<number>'.
    Property 'then' is missing in type 'IterableIterator<number>'.
```

**Additional information:**
This seems to be an issue with the definition of `ObservableInput<T>`:
```
export interface Subscribable<T> {
    subscribe(observerOrNext?: PartialObserver<T> | ((value: T) => void), error?: (error: any) => void, complete?: () => void): AnonymousSubscription;
}
export declare type SubscribableOrPromise<T> = Subscribable<T> | PromiseLike<T>;
export declare type ObservableInput<T> = SubscribableOrPromise<T> | ArrayLike<T>;
```

The iterable type is missing.

A fix might be to add:
```
export interface IterableLike<T> {
    [Symbol.iterator](): Iterator<T> | IterableIterator<T>;
}

// and fix ObservableInput<T>
export declare type ObservableInput<T> = SubscribableOrPromise<T> | ArrayLike<T> | IterableLike<T>;
```

**tsconfig.json**
```
{
	"compilerOptions": {
		"target": "es2015",
		"module": "commonjs",
		"moduleResolution": "node",
		"sourceMap": true,
		"alwaysStrict": true,
        "declaration": true,
		"noImplicitAny": true,
		"noImplicitThis": true,
		"strictNullChecks": true,
		"outDir": "dist",
		"lib": ["dom", "dom.iterable", "es2015", "es2015.iterable", "scripthost"]
	},
	"include": [
		"src"
	]
}
```

### PR DESCRIPTION
**Pull request by david-driscoll**
**Description:**
Now that TypeScript supports down level compilation, we can safely bring back `Iterable<T>` and `Iterator<T>`.

**Related issue (if exists):**
Fixes #2306 #2535

### CODE REVIEW

**Comment by david-driscoll** [comment]
cc @benlesh

File: src/observable/IteratorObservable.ts [hunk 1]
```diff
@@ -1,23 +1,32 @@
 import { root } from '../util/root';
 import { IScheduler } from '../Scheduler';
-import { Observable } from '../Observable';
+import { Observable, ArrayOrIterable } from '../Observable';
 import { iterator as Symbol_iterator } from '../symbol/iterator';
 import { TeardownLogic } from '../Subscription';
 import { Subscriber } from '../Subscriber';
+import { isArrayLike } from '../util/isArrayLike';
+
+export interface IteratorObservableState<T> {
```
Comment (kwonoj) [inline src/observable/IteratorObservable.ts]: is this need to be exported?

File: src/util/isIterable.ts [hunk 2]
```diff
@@ -0,0 +1,5 @@
+import { iterator as Symbol_iterator } from '../symbol/iterator';
+
+export function isIterable<T>(value: any): value is Iterable<T> {
```
Comment (kwonoj) [inline src/util/isIterable.ts]: generic param T is required?

Comment (david-driscoll) [inline src/util/isIterable.ts]: It helps flow the types through, `isPromise` and `isArrayLike` are also both generic.

File: src/observable/IteratorObservable.ts (hunk 1 above)
Comment (david-driscoll) [inline src/observable/IteratorObservable.ts]: Yes, compiler complains otherwise (because dispatch is public).  If we made dispatch private it probably wouldn't need to be.

Comment (kwonoj) [inline src/observable/IteratorObservable.ts]: I think we may need, I recall some of dispatch is private and interfaces are hidden already. No need to expose unnecessary interface.

**Comment by david-driscoll** [comment]
Updated

**Comment by david-driscoll** [comment]
cc @benlesh I can merge at will right? 🚢 😄

**Comment by HipsterZipster** [comment]
When is this getting released? I don't see it in RxJS@5.4.2
