### PR TITLE
Fix/5487 reentrancy in take, takeWhile, and first

### LINKED ISSUE #5487: first/tap operators should unsubscribe before emit next value
## Bug Report

**Current Behavior**

Currently, we are unsubscribing from source observables after emit the last message next to the chain. In some cases, it can raise incorrect and unexpected behavior (it seems to me).
In example below, we are still have processing new messages second observable in `merge` after `first` have emitted the first message. But expected behavior is that `first` operator must unsubscribe from all sources on receiving the first message.

Also, we have strange behavior: we can emit error from second observable and this exception will go through `first` operator and handle (in my example)  in `catchError`, but if we try to pass just a value through `first`, this operator (actually `tap` operator inside of `first`) will omit this message.

**Reproduction**

```js
const notificator = new Subject();

merge(
  timer(1)
    .pipe(
      tap((m) => console.log('value from first: ', m)),
    ),
  notificator.pipe(
    tap(() => console.log('value from notificator')),
    switchMap(() => throwError(new Error('Some error'))),
))
  .pipe(
    first(),
    catchError((err) => {
      console.log('Catching error: ', err)
      return throwError('Continue receive error after first value');
    }),
    tap((value) => {
      console.log('value: ', value);
      notificator.next(null);
    })
  ).subscribe(
    (value) => console.log('Next value: ', value),
    (err) => console.log('Error: ', err),
  );
```
Output:
```
value from first: 0
value: 0
value from notificator
Catching error: Error {}
Error: Continue receive error after first value
```

You can try it [here](https://stackblitz.com/edit/rxjs-etniuk).

**Expected behavior**

As I told before, I think that we shouldn't get any effects (include errors) from source observables after the limit of allowed values in stream reached. And more, we should unsubscribe from them, to prevent any calculations inside source chain, we should unsubscribe before passing the last value next.

**Environment**
- Runtime: Chrome/83.0.4103.97
- RxJS version: 6.5.2

**Possible Solution**

In `take` operator we overriding next handler to: 

https://github.com/ReactiveX/rxjs/blob/3f3c614d8b86c68d271a1db995ff11c61842e757/src/internal/operators/take.ts#L79-L89

I suggest changing them to make unsubscribe stuff before emitting next value. Also, this will allow us to omit ```if (count <= total)``` this strange check, because if we already unsubscribed from source that we will no longer receive a message.

If this change can affect something (backward compatibility), I think we should at least override `_error` handler to prevent passing errors. But I think, more correct just unsubscribe before next.

I will be glad to make a pull request if you agree with my arguments.

### PR DESCRIPTION
**Pull request by benlesh**
- fix(first/take): behave properly with reentrant errors and completions
    
    - Resolves an issue with both `first` and `take` where an error emitted by a reentrant source at the moment the last value it taken would result in superceding the expected emitted value and completion.
    - Resolves a similar issue where a reentrant completion would supercede the expected last value and completion

    Fixes #5487

- fix(takeWhile): reentrant errors and completions behave properly
    
    - Resolves an issue where a reentrant error notification would short circuit the completion.
    - Adds additional tests.

    Related #5487

- chore: Add reentrant error test for takeUntil

### CODE REVIEW

**Comment by benlesh** [comment]
Note: also fixes `elementAt` (because it uses `take`).

File: src/internal/operators/take.ts [hunk 1]
```diff
@@ -51,20 +51,41 @@ export function take<T>(count: number): MonoTypeOperatorFunction<T> {
...
               }
+            },
+            (err) => {
+              // If seen === count or higher, then we've already taken all of
+              // the values we were supposed to, and the error we're getting here
+              // is from reentrant code racing our `complete` above. We want to stop
+              // that here.
+              if (seen < count) {
+                subscriber.error(err);
+              }
```
Comment (backbone87) [inline src/internal/operators/take.ts:86]: out of interest: is there any particular reason, why blocking notifications over unsubscribing before the last next notification was used?

(besides the failing delayWhen test)

File: src/internal/operators/takeWhile.ts [hunk 2]
```diff
@@ -57,12 +57,34 @@ export function takeWhile<T>(predicate: (value: T, index: number) => boolean, in
...
+            // we found the "last" value, then we send the value along.
+            subscriber.next(value);
+          }
+          if (!taking) {
+            // We're no longer taking values after calling the predicate above
+            // time to complete the result.
+            subscriber.complete();
+          }
+        },
+        undefined,
```
Comment (backbone87) [inline src/internal/operators/takeWhile.ts:78]: we should probably also block complete notifications here, as was done in take

File: spec/operators/takeWhile-spec.ts [hunk 3]
```diff
@@ -364,4 +364,88 @@ describe('takeWhile', () => {
 
     expect(sideEffects).to.deep.equal([0, 1, 2]);
   });
+
+  it('should not emit errors sent from the source *after* it found the first value in reentrant scenarios', () => {
```
Comment (backbone87) [inline spec/operators/takeWhile-spec.ts:368]: if i revert the change in takeWhile, this test case isn't failing. to make it fail, i had to use:
```ts
        tap({
          next: (x) => {
            if (x === 'b') {
              subject.error(new Error('reentrant shennanigans'));
            }
          },
        })
```

**Review by Enuvid — COMMENTED** [review]
@cartant @benlesh @backbone87

Also i am not sure that fix of this problem right now will not affect already written code which used this behaviour. Seems that is a Breaking Change.

I mean do 'unsubscribe source before emit last value next'.

**Comment by benlesh** [comment]
Honestly, I'm inclined to say at some point we can't accommodate every crazy synchronous thing that someone wants to do with the library. It seems like we're going to have to introduce a good amount of complexity to the library in order to accommodate what is honestly a corner case, IMO. At a certain point, the simpler "fix" for this would be to give up and schedule everything.

Originally when I looked at the issue I closed it because I thought "well, this is expected behavior, honestly, it's just how things work". But then I saw we can code to protect against reentrancy in the `next` handler for `take`, and I reconsidered.

Fundamentally to really "solve" this in a way that satifisfies the requirements laid out here, we're going to need to expose some sort of "preteardown" or "stopping" method or flag on the `subscriber` to the world. I doubt the payoff is worth the confusion, but I'm willing to be convinced otherwise.

**Comment by benlesh** [comment]
```
finalize 1
1
done
finalize 2
```

It is completely unexpected. `1` and `done` should happen _before_ `finalize 1`.  The source emits 1, then completes, _then_ is `finalized`.

**Comment by benlesh** [comment]
Yeah... hmm..  in RxJS 6 and 7 (not sure about others), this is all kinds of weird/wrong:

```ts
let n = 0;

const subject = new Subject<number>();

merge(subject, of(n++))
  .pipe(
    finalize(() => {
      console.log('finalized');
    }),
    take(10),
    tap(() => subject.next(n++))
  )
  .subscribe({
    next: console.log,
    complete: () => console.log('done')
  });
  
// outputs 
// 9
// done
// finalized
```

**Comment by benlesh** [comment]
Okay... after some thought, and discussion with @cartant, I think the correct thing to do is to have it `unsubscribe` as soon as it knows it's done.

The principle behind this is simply that:

1. All operators create observables that are the consumers of a source.
2. The consumer should unsubscribe as soon as it knows it no longer wants any values from the source.

That said... this is a **BREAKING CHANGE** and we cannot have it until version 8.

File: spec/operators/take-spec.ts [hunk 4]
```diff
@@ -234,4 +234,47 @@ describe('take', () => {
...
+      )
+      .subscribe({
+        next: (n) => results.push(n),
+        complete: () => results.push('done'),
+      });
+
+    // Because this is reentrant, the last "taken" value of 5 is followed by `complete()`
+    // which shuts off all value emissions. Otherwise, this would be
+    // [5, 'done', 4, 3, 2, 1, 'finalize source', 'finalize result']
+    expect(results).to.deep.equal([5, 'done', 'finalize source', 'finalize result']);
```
Comment (backbone87) [inline spec/operators/take-spec.ts:276]: this one is weird. is this behavior we would be ok with? guess the solution would be to `subject.pipe(observeOn(asapScheduler))`

File: spec/operators/takeWhile-spec.ts [hunk 5]
```diff
@@ -364,4 +364,130 @@ describe('takeWhile', () => {
...
+          },
+        })
+      );
+
+      expectObservable(result).toBe(expected);
+      expectSubscriptions(source.subscriptions).toBe(subs);
+    });
+  });
+
+  it('should not emit completions sent from the source *after* it found the first value in reentrant scenarios', () => {
```
Comment (backbone87) [inline spec/operators/takeWhile-spec.ts:473]: does not fail on master either, but the same question as above: how to even test this?

File: spec/operators/takeWhile-spec.ts [hunk 6]
```diff
@@ -364,4 +364,130 @@ describe('takeWhile', () => {
...
+          }
+        })
+      );
+
+      expectObservable(result).toBe(expected);
+      expectSubscriptions(source.subscriptions).toBe(subs);
+    });
+  });
+
+  it('should not emit errors sent from the source *after* it found the first value in reentrant scenarios', () => {
```
Comment (backbone87) [inline spec/operators/takeWhile-spec.ts:431]: does not fail on master, but idk how to even test this one

File: spec/operators/takeWhile-spec.ts [hunk 7]
```diff
@@ -364,4 +364,130 @@ describe('takeWhile', () => {
...
+          },
+        })
+      );
+
+      expectObservable(result).toBe(expected);
+      expectSubscriptions(source.subscriptions).toBe(subs);
+    });
+  });
+
+  it('should not emit completions sent from the source *after* it found the first value in reentrant scenarios', () => {
```
Comment (backbone87) [inline spec/operators/takeWhile-spec.ts:452]: does not fail on master, had to use
```ts
        tap((x) => {
          if (x === 'b') {
            subject.complete();
          }
        })
```

File: src/internal/operators/take.ts (hunk 1 above)
Comment (benlesh) [reply src/internal/operators/take.ts]: Sorry for the late response. I'm not sure I understand your question here.

File: src/internal/operators/takeWhile.ts (hunk 2 above)
Comment (benlesh) [reply src/internal/operators/takeWhile.ts]: This has been added.

File: spec/operators/takeWhile-spec.ts (hunk 3 above)
Comment (benlesh) [reply spec/operators/takeWhile-spec.ts:368]: Seems this was fixed by a later commit (sorry, revisiting this)

File: spec/operators/takeWhile-spec.ts (hunk 7 above)
Comment (benlesh) [reply spec/operators/takeWhile-spec.ts:452]: This would not be testing the same thing, exactly.

Ultimately, this and the test below it are really just exercising the subscriber guarantees. But nonetheless I think we should keep them so someone doesn't implement something in the future that breaks this contract.

**Review by jakovljevic-mladen — APPROVED** [review]
LGTM
