### PR TITLE
docs(distinctUntilChanged): fix docs rendering

### LINKED ISSUE #6660: "distinctUntilChanged", "retry" and "timeoutWith" docs are not rendered properly
- [ ] The [`distinctUntilChanged`](https://rxjs.dev/api/operators/distinctUntilChanged) operator docs is not being rendered properly. Please check the image:

  distinctUntilChanged

  The operator [implementation](https://github.com/ReactiveX/rxjs/blob/62aca850a3/src/internal/operators/distinctUntilChanged.ts), however, contains the documentation, but for some reason, it is spread across multiple overloaded functions, so this might be causing the problems.

  Proposed fix in #6756.

- [x] The same case is with [`retry`](https://rxjs.dev/api/operators/retry) operator:

  retry

  Fixed in #6850.

- [x] And [`timeoutWith`](https://rxjs.dev/api/operators/timeoutWith) operator:

  image

  Fixed in #6858.

### PR DESCRIPTION
**Pull request by jakovljevic-mladen**
**Description:**
Please check the related issue for more info. This is how the page looks like with this fix (sorry for the large image):

image

One note: I'm not an expert, but it looks like that having multiple JSDocs comments on the same function overload (for two or more overloads) don't really work with the docs rendering scripts. Maybe there is an option to turn it on, but for now, all documentation should be contained in one JSDocs comment (`/** here */`) instead of having it in multiple comments (for example, one for each overload).

**Related issue (if exists):**
Closes #6660

### CODE REVIEW

File: src/internal/operators/distinctUntilChanged.ts [hunk 1]
```diff
@@ -3,19 +3,38 @@ import { identity } from '../util/identity';
...
+ * When provided without parameters or with the first parameter (`{@link distinctUntilChanged#comparator comparator}`),
+ * it behaves like this:
+ *
  * 1. It will always emit the first value from the source.
  * 2. For all subsequent values pushed by the source, they will be compared to the previously emitted values
  *    using the provided `comparator` or an `===` equality check.
  * 3. If the value pushed by the source is determined to be unequal by this check, that value is emitted and
  *    becomes the new "previously emitted value" internally.
  *
+ * When the second parameter (`{@link distinctUntilChanged#keySelector keySelector}`) is provided, the behavior
```
Comment (jakovljevic-mladen) [inline src/internal/operators/distinctUntilChanged.ts:25]: The link here doesn't really work for now:

image

But, I'll try to fix it later. This is how this looks like:

image

File: src/internal/operators/distinctUntilChanged.ts [hunk 2]
```diff
@@ -127,17 +126,16 @@ export function distinctUntilChanged<T>(comparator?: (previous: T, current: T) =
...
  * equality. Defaults to a `===` check.
  * @param keySelector Used to select a key value to be passed to the `comparator`.
+ *
  * @return A function that returns an Observable that emits items from the
  * source Observable with distinct values.
  */
-export function distinctUntilChanged<T, K>(
-  comparator: (previous: K, current: K) => boolean,
-  keySelector: (value: T) => K
-): MonoTypeOperatorFunction<T>;
```
Comment (jakovljevic-mladen) [inline src/internal/operators/distinctUntilChanged.ts:139]: Moved to [top](https://github.com/ReactiveX/rxjs/pull/6756/files#diff-9be4aaa20e2c54b85cde0eb41759c61348e0868293683c9e836107120c0b103dR6-R10).

File: src/internal/operators/distinctUntilChanged.ts [hunk 3]
```diff
@@ -80,28 +99,8 @@ import { OperatorSubscriber } from './OperatorSubscriber';
...
-/**
- * Returns a result {@link Observable} that emits all values pushed by the source observable if they
- * are distinct in comparison to the last value the result observable emitted.
- *
- * 1. It will always emit the first value from the source.
- * 2. The `keySelector` will be run against all values, including the first value.
- * 3. For all values after the first, the selected key will be compared against the key selected from
- *    the previously emitted value using the `comparator`.
- * 4. If the keys are determined to be unequal by this check, the value (not the key), is emitted
- *    and the selected key from that value is saved for future comparisons against other keys.
```
Comment (jakovljevic-mladen) [inline src/internal/operators/distinctUntilChanged.ts:99]: Moved [here](https://github.com/ReactiveX/rxjs/pull/6756/files#diff-9be4aaa20e2c54b85cde0eb41759c61348e0868293683c9e836107120c0b103dR28).

**Review by benlesh — APPROVED** [review]
