### PR TITLE
fix(bindNodeCallback): emit undefined when callback has no success ar…

### LINKED ISSUE #2254: bindNodeCallback returns incorrect result if undefined success argument in callback
**RxJS version:**
5.0.0-beta.6 but bug is present in master as of f8ba77d8d933608caae7c2b25aaa8467eb9e8f3d

**Code to reproduce:**
````
let nodeFunction = function(param1: string, param2: string, callback: any) {
  // Bug only manifests when success parameter is implicitly undefined
  callback(null /*error*/); // no success parameter
}

Observable.bindNodeCallback(nodeFunction)('a', 'b')
  .subscribe(succ => console.log(succ));

````

**Expected behavior:**
`undefined`

**Actual behavior:**
`[]`

**Additional information:**
This is a bug IMO because it does not preserve the behaviour of the wrapped method. There are actual libraries in production that have this behaviour, e.g. [node-sqlite3](https://github.com/mapbox/node-sqlite3/wiki/API#databasegetsql-param--callback) (which is how I found it):

> **Database#get(sql, [param, ...], [callback])**
> 
> Runs the SQL query with the specified parameters and calls the callback with the first result row afterwards [...] The signature of the callback is function(err, row) {}. **If the result set is empty, the second parameter is undefined**, otherwise it is an object containing the values for the first row.

The problem appears to be in this line:
https://github.com/ReactiveX/rxjs/blob/master/src/observable/BoundNodeCallbackObservable.ts#L109

It could be fixed with something like this:
````
if(!innerArgs.length) {
  subject.next(undefined);
} else {
  subject.next(innerArgs.length === 1 ? innerArgs[0] : innerArgs);
}
````

But there's probably a more elegant way of doing it!

### PR DESCRIPTION
**Pull request by Podlas29**
**Description:**

Currently when callback is called without success arguments (second and following arguments),
`bindNodeCallback` emits empty array.

In RxJS 4 `undefined` is emitted instead as can be seen here:
https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/perf/operators/fromnodecallback.js#L23-L24
(when results array is empty `results[0]` returns `undefined` which is then emitted)

**Related issue (if exists):**
Related issue with `bindCallback` #2328 
Closes #2254

### CODE REVIEW

File: spec/observables/bindNodeCallback-spec.ts [hunk 1]
```diff
@@ -8,6 +8,24 @@ const Observable = Rx.Observable;
...
+      function callback(cb) {
+        cb(null);
+      }
+
+      const boundCallback = Observable.bindNodeCallback(callback);
+      const results = [];
+
+      boundCallback()
+        .subscribe((x: any) => {
+          results.push(typeof x);
```
Comment (kwonoj) [inline spec/observables/bindNodeCallback-spec.ts]: just curiosity, is there reason to push type instead of actual value to assert with `undefined` directly?

Comment (Podlas29) [inline spec/observables/bindNodeCallback-spec.ts]: I guess just habit of "everyone can set undefined value, so never trust it". All JS resources used to be very paranoid when I was learning. ;)
