### PR TITLE
fix: forkJoin/combineLatest return Observable<unknown> if passed any

### LINKED ISSUE #6226: Types: `forkJoin(any)` and `combineLatest(any)` return the wrong thing
```ts
// FAIL: Gives us Observable<{ [key: string]: unknown }>
const source1 = forkJoin([of(1), of(2)] as any); // $ExpectType Observable<unknown>

// FAIL: Gives us Observable<{ [key: string]: unknown }>
const source2 = combineLatest([of(1), of(2)] as any); // $ExpectType Observable<unknown>
```

Basically, if we get an `any` to either one of these, we have no way of knowing if we're getting back an array or an object, so we need to return `unknown`.

### PR DESCRIPTION
**Pull request by benlesh**
Resolves #6226

### CODE REVIEW

File: src/internal/AnyCatcher.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export interface AnyCatcher {
```
Comment (benlesh) [inline src/internal/AnyCatcher.ts:1]: LOLOLOLOLOLOLOLOL 🤣 🎉

File: src/internal/AnyCatcher.ts [hunk 2]
```diff
@@ -0,0 +1,3 @@
...
+  '@@@@@@CATCH_ANY_WITH_THIS@@@@@@@@': 'wat';
```
Comment (DanielRosenwasser) [inline src/internal/AnyCatcher.ts:2]:
```suggestion
  readonly ' @@@@@@CATCH_ANY_WITH_THIS@@@@@@@@': 'wat';
```

File: src/internal/observable/combineLatest.ts [hunk 3]
```diff
@@ -47,6 +48,12 @@ export function combineLatest<A extends readonly unknown[]>(
 
 // combineLatest({a, b, c})
 export function combineLatest(sourcesObject: { [K in any]: never }): Observable<never>;
+/**
+ * You have passed `any` here, we can't figure out if it is
+ * an array or an object, so you're getting `unknown`. Use better types.
+ * @param arg Something typed as `any`
+ */
+export function combineLatest<T extends AnyCatcher>(arg: T): Observable<unknown>;
```
Comment (cartant) [inline src/internal/observable/combineLatest.ts:56]: suggestion: I would make this the first signature. IDK why `any` skips all of the signatures above this one and I would not like to rely upon that behaviour never changing. There should be no reason this signature cannot be the first.

File: src/internal/observable/forkJoin.ts [hunk 4]
```diff
@@ -27,6 +28,12 @@ export function forkJoin<A extends readonly unknown[], R>(
 
 // forkJoin({a, b, c})
 export function forkJoin(sourcesObject: { [K in any]: never }): Observable<never>;
+/**
+ * You have passed `any` here, we can't figure out if it is
+ * an array or an object, so you're getting `unknown`. Use better types.
+ * @param arg Something typed as `any`
+ */
+export function forkJoin<T extends AnyCatcher>(arg: T): Observable<unknown>;
```
Comment (cartant) [inline src/internal/observable/forkJoin.ts:36]: suggestion: Make this the first overload signature.

File: src/internal/AnyCatcher.ts (hunk 1 above)
Comment (cartant) [reply src/internal/AnyCatcher.ts:9]: suggestion: This could be something like this, instead:

```ts
declare const anyCatcherSymbol: unique symbol;
type AnyCatcher = typeof anyCatcherSymbol;
```

[TypeScript Playground demo](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3lFBPAwlBmABYgwDKuAtgEZIQBc8ArigJYCOLCaN9EANwBYAFAZcABwQBBPIWJkY8ALzwJ0pADNs8oqXJU6DEaLGhIsBFrZgM7VPC0AeACrwQADwwgUwNPByBPpKAHwAFLAA5syuAJTMbADWKEgA7iimFtBwTrb2ji6uEdGxCfCupmLI6FhQqk7hAERQTdgBOLhxgvAA9L2sKCnpKNWomPC0DVrNtE3dfQNNc0A)

Comment (benlesh) [reply src/internal/AnyCatcher.ts:9]: Yeah, that's what I was saying on Slack, but it's SO BORING. Haha. Okay fine.

File: src/internal/observable/combineLatest.ts (hunk 3 above)
Comment (benlesh) [reply src/internal/observable/combineLatest.ts]: That's a really good idea!

**Review by cartant — APPROVED** [review]
