### PR TITLE
fix: useDeprecatedSynchronousErrorThrowing honored for flattened sync sources

### LINKED ISSUE #5983: Super gross mode no longer sync throws flattened errors
Given this code: 

```ts
import { throwError, of, config } from "rxjs";
import { concatMap } from "rxjs/operators";

console.clear();

config.useDeprecatedSynchronousErrorHandling = true;

try {
  of(1)
    .pipe(concatMap(() => throwError(new Error("test"))))
    .subscribe(console.log);
} catch (err) {
  console.log("Caught!", err);
}
```

It should log `"Caught!"` and the error, but it does not.

Related: #5979 

cc @leggechr

### PR DESCRIPTION
**Pull request by benlesh**
fixes #5983

### CODE REVIEW

File: src/internal/Subscriber.ts [hunk 1]
```diff
@@ -132,46 +132,40 @@ export class SafeSubscriber<T> extends Subscriber<T> {
...
+      next = next?.bind(context);
+      error = error?.bind(context);
+      complete = complete?.bind(context);
     }
+
+    // Once we set the destination, the superclass `Subscriber` will
+    // do it's magic in the `_next`, `_error`, and `_complete` methods.
+    this.destination = {
+      next: next ? maybeWrapForDeprecatedSyncErrorHandling(next, this) : noop,
+      error: maybeWrapForDeprecatedSyncErrorHandling(error ? error : defaultErrorHandler, this),
```
Comment (benlesh) [inline src/internal/Subscriber.ts:166]: The meat of the change is here.

File: src/internal/Subscriber.ts [hunk 2]
```diff
@@ -132,46 +132,40 @@ export class SafeSubscriber<T> extends Subscriber<T> {
   ) {
     super();
 
-    // If we don't have arguments, or the observer passed is already EMPTY_OBSERVER,
-    // use EMPTY_OBSERVER. This is just to save a little on object allocations.
-    this.destination = EMPTY_OBSERVER;
-    if ((observerOrNext || error || complete) && observerOrNext !== EMPTY_OBSERVER) {
```
Comment (benlesh) [inline src/internal/Subscriber.ts:138]: After some thought, I realized that this check, and setting `this.destination = EMPTY_OBSERVER` was pointless, so that got removed.

It might be better to review this with "ignore whitespace" on.

**Review by kwonoj — APPROVED** [review]
ugh(2).
