### PR TITLE
fix: `share` and `connect` no longer bundle scheduling code by default

### LINKED ISSUE #6872: Don't use `from(x)` in the library, use `innerFrom`
Cases where we are using `from(x)` instead of `innerFrom(x)` cause the inclusion of `scheduled`, which then includes a host of other things, `observeOn`, `subscribeOn`, etc.

Related to conversation here https://github.com/trpc/trpc/pull/1592#issuecomment-1062462319

### PR DESCRIPTION
**Pull request by benlesh**
resolves #6872

### CODE REVIEW

**Comment by benlesh** [comment]
Before: 

image

After:

image

File: src/internal/observable/innerFrom.ts [hunk 1]
```diff
@@ -12,6 +12,7 @@ import { isFunction } from '../util/isFunction';
 import { reportUnhandledError } from '../util/reportUnhandledError';
 import { observable as Symbol_observable } from '../symbol/observable';
 
+export function innerFrom<O extends ObservableInput<any>>(input: O): Observable<ObservedValueOf<O>>;
```
Comment (cartant) [inline src/internal/observable/innerFrom.ts:15]: Can we just change the signature instead of adding an overload signature - which will hide the implementation signature anyway?

**Review by cartant — APPROVED** [review]

File: src/internal/observable/innerFrom.ts (hunk 1 above)
Comment (benlesh) [reply src/internal/observable/innerFrom.ts:15]: I did that and the guts of the implementation hated me for it. I'll fiddle with it again before I merge it, but I figure it's not super important since it's not a publicly exposed function.

Comment (benlesh) [reply src/internal/observable/innerFrom.ts:15]: Upon review. I'm going to do a follow up PR on this, because I think maybe there are some issues with `onErrorResumeNext`'s types.
