### PR TITLE
fix(takeLast): fix takeLast behavior to emit correct order

### LINKED ISSUE #1407: takeLast bug
```js
var foo = Rx.Observable.interval(1000);

var bar = foo.take(5).takeLast(3);

bar.subscribe(
  function (x) { console.log('next ' + x); },
  function (err) { console.log('error ' + err); },
  function () { console.log('done'); },
);
```

This outputs:
```
"next 3"
"next 4"
"next 2"
"done"
```

When it should output
```
"next 2"
"next 3"
"next 4"
"done"
```

Happened with beta.2

- - -

And 
```js
var bar = foo.take(5).takeLast(2);
```

Caused output
```
"next 4"
"next undefined"
"done"
```

### PR DESCRIPTION
**Pull request by kwonoj**
closes #1407 

This PR tries to fix behavior of `takeLast` by changing ring buffer indexing routines. Maybe I miss something, but so far it looks work correctly.

/cc @staltz for visibility.

### CODE REVIEW

**Comment by kwonoj** [comment]
Found one failure cases, marking as blocked for now.

**Comment by staltz** [comment]
Nice! Thanks for the fix

File: spec/operators/takeLast-spec.ts [hunk 1]
```diff
@@ -14,6 +14,46 @@ describe('Observable.prototype.takeLast()', () => {
...
+  it('should take all element when try to take exact', (done: DoneSignature) => {
+    const expected = [0, 1, 2];
+
+    Observable.of(0, 1, 2).takeLast(3).subscribe((x) => {
+      expect(x).toBe(expected.shift());
+    }, done.fail, () => {
+      expect(expected.length).toBe(0);
+      done();
+    });
+  });
```
Comment (blesh) [inline spec/operators/takeLast-spec.ts]: Can we change the above tests to use marble diagrams and virtual scheduling?

Comment (kwonoj) [inline spec/operators/takeLast-spec.ts]: I think so, let me do that.

Comment (blesh) [inline spec/operators/takeLast-spec.ts]: I don't mind keeping one synchronous test, of course, but the marble tests are more analogous to the issue that was reported (which was using an interval).

**Comment by kwonoj** [comment]
Updated PR to use marble diagram for test cases.

File: spec/operators/takeLast-spec.ts [hunk 2]
```diff
@@ -14,6 +14,40 @@ describe('Observable.prototype.takeLast()', () => {
     expectSubscriptions(e1.subscriptions).toBe(e1subs);
   });
 
+  it('should take last three values', () => {
+    const e1 =  cold('--a-----b----c---d--|    ');
+    const e1subs =   '^                   !    ';
+    const expected = '--------------------(bcd|)';
```
Comment (staltz) [inline spec/operators/takeLast-spec.ts]: Much nicer

**Comment by kwonoj** [comment]
Merged with 73eb658.
