### PR TITLE
Observe on leak

### LINKED ISSUE #2244: Memory Leak with Queue Scheduler and Subject
**RxJS version:** 5.0.2

**Code to reproduce:**
Observing a subject using the `queue` scheduler creates many `QueueAction`s that are never freed.

Plnkr demonstrating issue: https://plnkr.co/edit/BBkHlpIf6MiP2eOPdIlz

Minimal code to reproduce:
```ts
import 'rxjs/add/operator/observeOn';
import { interval } from 'rxjs/observable/interval';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { queue } from 'rxjs/scheduler/queue';

const source$ = new BehaviorSubject(0);

source$.observeOn(queue).subscribe();

interval(50).subscribe(source$);
```

Create two heap allocation snapshots about 20 seconds apart and use the comparison tools to see the allocation delta. Example:

Heap Allocation Snapshot Example

**Expected behavior:**
No memory leak of previous values.

**Actual behavior:**
Previous values are retained in `QueueAction`s

### PR DESCRIPTION
**Pull request by blesh**
- ensures child subscriptions created via `Subscription.prototype.add` remove themselves from the internal subscriptions list.
- ensures scheduled notifications from observeOn remove themselves from the subscription by calling unsubscribe on themselves.

fixes #2244

### CODE REVIEW

File: src/scheduler/VirtualTimeScheduler.ts [hunk 1]
```diff
@@ -54,15 +54,13 @@ export class VirtualAction<T> extends AsyncAction<T> {
   }
 
   public schedule(state?: T, delay: number = 0): Subscription {
-    return !this.id ?
-      super.schedule(state, delay) : (
-      // If an action is rescheduled, we save allocations by mutating its state,
```
Comment (trxcllnt) [inline src/scheduler/VirtualTimeScheduler.ts]: @blesh can we keep this comment?

Comment (blesh) [inline src/scheduler/VirtualTimeScheduler.ts]: 👍

**Comment by trxcllnt** [comment]
lgtm

**Comment by kudoz83** [comment]
Is there an estimate on when the next patch version will be available?

**Comment by blesh** [comment]
@kudoz very soon. This week or early next week.
