### PR TITLE
fix(TestScheduler): stop sorting actual results

### LINKED ISSUE #422: Merge semantics for race conditions between synchronous notifications
This is probably a bug.

While making tests for mergeMap I wrote this marble test based on a RxJS 4 test:

```js
  it('should mergeMap many regular interval inners', function () {
   var a =   cold('----a---a---a---(a|)'                    );
   var b =   cold(    '----b---b---(b|)'                    );
   var c =   cold(                '----c---c---c---c---(c|)');
   var d =   cold(                        '----(d|)'        );
   var e1 =   hot('a---b-----------c-------d-------|'       );
   var expected = '----a---(ba)(ba)(ba)c---c---(dc)c---(c|)';
  
   var observableLookup = { a: a, b: b, c: c, d: d };
   var source = e1.mergeMap(function (value) {
     return observableLookup[value];
   });
  
   expectObservable(source).toBe(expected);
  });
```

Notice 

`var expected = '----a---(ba)(ba)(ba)c---c---(dc)c---(c|)'`

This test passes for RxJS 4, but does not pass for RxJS Next, which behaves like this

`var expected = '----a---(ba)(ab)(ab)c---c---(cd)c---(c|)'`

I quickly took a look and tried to solve this for mergeMap, but the problem seemed deeper, related to `subscribeToResult`, `InnerSubscriber`, and potentially from `TestScheduler` and `VirtualTimeScheduler` too. Might affect many operators, so was beyond the scope of my mergeMap PR #423.

### PR DESCRIPTION
**Pull request by blesh**
- fixes an issue where actual results were being sorted when they should not have been
- ensures rescheduled Actions will be added to subscription and torn down when appropriate
- uses state to convey notification information to action work function rather than closure

closes #422

### CODE REVIEW

**Comment by blesh** [comment]
I'm going to merge this one right away, since it fixes critical bugs with the test scheduler.

File: spec/operators/merge-map-spec.js [hunk 1]
```diff
@@ -1,8 +1,25 @@
...
 var Promise = require('promise');
 
 describe('Observable.prototype.mergeMap()', function () {
+  it('should mergeMap many regular interval inners', function () {
+    var a =   cold('----a---a---a---(a|)'                    );
+    var b =   cold(    '----b---b---(b|)'                    );
+    var c =   cold(                '----c---c---c---c---(c|)');
+    var d =   cold(                        '----(d|)'        );
+    var e1 =   hot('a---b-----------c-------d-------|'       );
+    var expected = '----a---(ab)(ab)(ab)c---c---(cd)c---(c|)';
```
Comment (staltz) [inline spec/operators/merge-map-spec.js]: It finally looks like it should. (ab) :+1:

File: src/testing/ColdObservable.ts [hunk 2]
```diff
@@ -29,12 +29,11 @@ export default class ColdObservable<T> extends Observable<T> implements Subscrip
   scheduleMessages(subscriber) {
     const messagesLength = this.messages.length;
     for (let i = 0; i < messagesLength; i++) {
-      const message = this.messages[i];
+      let message = this.messages[i];
```
Comment (staltz) [inline src/testing/ColdObservable.ts]: Is there a reason behind this? Do we default to `let`?

Comment (blesh) [inline src/testing/ColdObservable.ts]: No. It was probably residue from me fiddling with code while debugging
