### PR TITLE
fix(reduce): fix overload ordering

### LINKED ISSUE #2338: Reduce logs as array, but erroring as object
**RxJS version:**
5.1.0

**Code to reproduce:**
```typescript
this.searchSubscription = this.filtersSubject
  .takeLast(2)
  .reduce((acc, cur) => {
    console.log(acc);
    acc.push(cur);
    return acc;
  }, [])
  .debounceTime(1000)
  .subscribe(x => this.emitFilters());
```

**Error:**
Code fails to compile because error claiming acc is an object (thus, no push method), even though the console.log shows acc to be an array.

**Additional information:**
I was told by [this StackOverflow answer](http://stackoverflow.com/questions/42080580/rxjs-reduce-logs-as-array-but-erroring-as-object#42080580) that this is a bug with RxJS? If I'm wrong, please ignore.

### PR DESCRIPTION
**Pull request by aluanhaddad**
**Description:**
Type inference for `Observable.prototype.reduce` currently behaves incorrectly, resulting in spurious type errors, in many common cases, when the type of `seed` is a different type than the value type of the Observable.

One of the declared overloads is intended to specifically cater to this scenario but fails to do so because of its ordering with respect to the other overload declared.

The overload in question takes two type arguments, `T` and `R`, making it more specific than the overloads declared before it.

Due to TypeScript's overload resolution algorithm, which picks the first matching overload, this overload does not have the intended effect.

This is documented here https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html in the section entitled **Function Overloads**, under the **Ordering** heading, which states

> Don’t put more general overloads before more specific overloads:

> Do sort overloads by putting the more general signatures after more specific signatures:

> Why: TypeScript chooses the first matching overload when resolving function calls. When an earlier overload is “more general” than a later one, the later one is effectively hidden and cannot be called.

**Related issue (if exists):**
This fixes #2338

### CODE REVIEW

**Comment by aluanhaddad** [comment]
@kwonoj Thank you, I most definitely will.

**Comment by aluanhaddad** [comment]
It looks like there is more nuance here, the overload taking an array seems to be producing more issues than I had thought.

**Comment by blesh** [comment]
@aluanhaddad it looks like there are build errors with the specs. Do you think you can fix them?

**Comment by aluanhaddad** [comment]
Yes I've been very busy recently. I will try to fix them tonight and add some additional tests as well. When I looked at the specs, they seemed to rely on the seed being inferred to have the value type of the Observable. I need to double-check if that is the case.
Perhaps I misunderstand the behavior of RxJS or the intent of the Declarations but this doesn't seem like a reasonable assumption at face value.

**Comment by aluanhaddad** [comment]
I am having some trouble replicating the test failures locally.
When I run
```bash
npm run build_spec && npm run test_mocha && node ./node_modules/markdown-doctest/bin/cmd.js
```
Any tips would be greatly appreciated.

**Comment by aluanhaddad** [comment]
@kwonoj I added several new test including tests covering behavior that was an error before these changes.
@blesh I fixed the failing tests and also broke them down into multiple discrete tests, for assignability.

I added a local binding and a subsequent statement to each test I touched so that the resulting value is now used in such a way that it validates that the types are propagated.

Let me know if these tests are sufficient and also let me know if I should have added the same tests to `spec/operator/scan-spec`.

**Comment by kwonoj** [comment]
I think this change is ready, re-approving. /cc @david-driscoll for second eye just in case.

File: spec/operators/reduce-spec.ts [hunk 1]
```diff
@@ -302,23 +302,84 @@ describe('Observable.prototype.reduce', () => {
...
+      });
     });
   });
 
-  it('should accept R typed reducers', () => {
+  it('should accept R typed reducers and reduce to type R', () => {
     type(() => {
       let a: Rx.Observable<{ a: number; b: string }>;
-      a.reduce<{ a?: number; b?: string }>((acc, value) => {
+      const reduced = a.reduce<{ a?: number; b?: string }>((acc, value) => {
```
Comment (masaeedu) [inline spec/operators/reduce-spec.ts]: Is a separate test required for generic type argument inference of `R`?

**Comment by masaeedu** [comment]
lgtm

File: spec/operators/reduce-spec.ts (hunk 1 above)
Comment (aluanhaddad) [inline spec/operators/reduce-spec.ts]: I believe so. Failure to infer `R` as distinct from `T` and `T[]` was the original issue.

Comment (masaeedu) [inline spec/operators/reduce-spec.ts]: @aluanhaddad This test doesn't seem to be verifying correct inference, because it specifies the generic type arg explicitly. Probably for an inference test you'd repeat this without the explicit type argument, then try to assign `reduced` to a variable of the explicit type you expect to have been inferred.

Comment (masaeedu) [inline spec/operators/reduce-spec.ts]: My bad, just realized the "R is not assignable to T" test already covers inference. 👍

**Comment by benlesh** [comment]
@david-driscoll can you review this please? <3

**Comment by aluanhaddad** [comment]
Just to note, when I first looked at this, I believed the issue was simply due to the overload ordering but the root cause turned out to have as much to do with the optionality of the seed arguments as signature ordering. The now required seed arguments eliminate a previously applicable overload from the candidate set, but a minor order change was still ultimately necessary.

**Comment by benlesh** [comment]
Thanks @aluanhaddad !!!
