### PR TITLE
fix: finalize behaves well with useDeprecatedSynchronousErrorHandling

### LINKED ISSUE #6250: finalize not firing in super gross mode
When using `useDeprecatedSynchronousErrorHandling`, `finalize` handlers are not called after a synchronous error is thrown

This is nefarious, because it means that maybe we're not calling any teardowns at all.

```ts
import { throwError, config } from "rxjs";
import { finalize } from "rxjs/operators";
console.clear();

config.useDeprecatedSynchronousErrorHandling = true;

try {
  throwError(new Error("test"))
    .pipe(
      finalize(() => {
       // This is never called.
        console.log("finalized");
      })
    )
    .subscribe(() => {
      console.log("nexted");
    });
} catch (err) {
  console.log("here");
}
```

### PR DESCRIPTION
**Pull request by benlesh**
Adds tests and ensures a few more scenarios that were hit in Google because they use the deprecated synchronous error handling.

fixes #6250

cc @leggechr

### CODE REVIEW

File: src/internal/Observable.ts [hunk 1]
```diff
@@ -215,43 +215,67 @@ export class Observable<T> implements Subscribable<T> {
...
+            this._subscribe(subscriber)
+          : // In all other cases, we're likely wrapping a user-provided initializer
+            // function, so we need to catch errors and handle them appropriately.
+            this._trySubscribe(subscriber)
+      );
     }
+    return subscriber;
+  }
 
-    subscriber.add(
```
Comment (benlesh) [inline src/internal/Observable.ts:232]: I split this up, and added comments. Just for organizational reasons more than anything.

File: src/internal/Observable.ts [hunk 2]
```diff
@@ -215,43 +215,67 @@ export class Observable<T> implements Subscribable<T> {
...
+    let dest: any = subscriber;
+    dest._syncErrorHack_isSubscribing = true;
+    const { operator } = this;
+    if (operator) {
+      // We don't need to try/catch on operators, as they
+      // are doing their own try/catching, and will
+      // properly decorate the subscriber with `__syncError`.
+      subscriber.add(operator.call(subscriber, this.source));
+    } else {
+      try {
```
Comment (benlesh) [inline src/internal/Observable.ts:253]: the primary "fix" is here for the cases where teardown wasn't being called after it was registered if a sync error was thrown.

File: src/internal/operators/finalize.ts [hunk 3]
```diff
@@ -58,7 +58,12 @@ import { operate } from '../util/lift';
  */
 export function finalize<T>(callback: () => void): MonoTypeOperatorFunction<T> {
   return operate((source, subscriber) => {
-    source.subscribe(subscriber);
-    subscriber.add(callback);
+    // TODO: This try/finally was only added for `useDeprecatedSynchronousErrorHandling`.
+    // REMOVE THIS WHEN THAT HOT GARBAGE IS REMOVED IN V8.
+    try {
```
Comment (benlesh) [inline src/internal/operators/finalize.ts:63]: The "fix" for the finalize issue in the sync case is here. Note that adding a callback to a `closed` subscriber will cause it to be executed immediately.

**Review by cartant — APPROVED** [review]
🤢

**Comment by cartant** [comment]
Do we have tests that are the equivalent of these but are for the normal error handling - not the deprecated synchronous error handling. Seems like something worth testing if we're not already doing that.

**Comment by benlesh** [comment]
@cartant I'm unsure. I'll have a look after I merge this.
