### PR TITLE
fix: Observable teardowns now properly called if `useDeprecatedSynchronousErrorHandling` is `true`.

### LINKED ISSUE #6364: useDeprecatedSynchronousErrorHandling not calling teardown if synchronously unsubscribed
Found in google3 (of course, haha) cc @leggechr 

```ts
import { Observable, config } from "rxjs";

config.useDeprecatedSynchronousErrorHandling = true;

let called = false;
const observable = new Observable(obs => () => (called = true));
const subscription = observable.subscribe();
subscription.unsubscribe();

console.log("called: ", called); // logs called: false
```

https://stackblitz.com/edit/rxjs-4stiyw?devtoolsheight=60

### PR DESCRIPTION
**Pull request by benlesh**
Resolves an issue where teardowns returned by the Observable initializer were not being registered with the subscriber.

Fixes #6364

cc @leggechr

### CODE REVIEW

File: spec/Observable-spec.ts [hunk 1]
```diff
@@ -810,6 +810,24 @@ describe('Observable', () => {
         }).not.to.throw();
       });
 
+      it('should call teardown if sync unsubscribed', () => {
```
Comment (benlesh) [inline spec/Observable-spec.ts:813]: This is the only test that was failing. I just added the other one to cover the other scenario.

File: src/internal/Observable.ts [hunk 2]
```diff
@@ -252,7 +252,7 @@ export class Observable<T> implements Subscribable<T> {
       subscriber.add(operator.call(subscriber, this.source));
     } else {
       try {
-        this._subscribe(subscriber);
+        subscriber.add(this._subscribe(subscriber));
```
Comment (benlesh) [inline src/internal/Observable.ts:255]: 🤦

**Review by cartant — APPROVED** [review]
