### PR TITLE
fix(pluck): operator breaks with null/undefined inputs.

### LINKED ISSUE #5505: Pluck operator doesn't fully check for null or undefined
If I have a source that emits a nullish value and try to use `pluck`, I get an error.

```typescript
const source = of(null).pipe(pluck('someProp'));
source.subscribe();
// ERROR TypeError: Cannot read property 'someProp' of null
```

I think it would be nice if `pluck` checked for this and returned `undefined`.

```typescript
const source = of(null).pipe(pluck('someProp'));
source.subscribe(console.log);
// logs: undefined
```

[The description of this operator even says](https://github.com/ReactiveX/rxjs/blob/78032157f5c1655436829017bbda787565b48c30/src/internal/operators/pluck.ts#L25), "If a property can't be resolved, it will return `undefined` for that value." Seems to make sense that it would do the same for the value whose property we're checking as well.

This would be especially helpful when trying to get more deeply nested values.

```typescript
interface Person {
  name: Name | null;
  pet: {
    name: Name | null;
  }
}
interface Name {
  first: string,
  last: string
}
const person: Person = { name: null, pet: { name: null } };
const petFirstName = of(person).pipe(pluck('pet', 'name', 'first'));
source.subscribe(console.log);
// logs: undefined
```

---

Looking at the source code, [I see this](https://github.com/ReactiveX/rxjs/blob/78032157f5c1655436829017bbda787565b48c30/src/internal/operators/pluck.ts#L59):
```typescript
const mapper = (x: string) => {
  let currentProp = x;
  for (let i = 0; i < length; i++) {
    const p = currentProp[props[i]];
    if (typeof p !== 'undefined') {
      currentProp = p;
    } else {
      return undefined;
    }
  }
  return currentProp;
};
```

Seems like it could be as simple as changing
```typescript
const p = currentProp[props[i]];
```
to
```typescript
const p = currentProp && currentProp[props[i]];
```

**P.S.** Why in the `mapper` function is `x` of type `string`? Wouldn't it be an object?

### PR DESCRIPTION
**Pull request by anirudhvarma12**
**Description:**
Add a fix to prevent the pluck operator from breaking on null or undefined inputs. 

**Related issue (if exists):**
https://github.com/ReactiveX/rxjs/issues/5505

### CODE REVIEW

File: src/internal/operators/pluck.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ export function pluck<T, R>(...properties: Array<string | number | symbol>): Ope
   return map((x) => {
     let currentProp: any = x;
     for (let i = 0; i < length; i++) {
-      const p = currentProp[properties[i]];
+      const p = currentProp?.[properties[i]] ?? undefined;
```
Comment (cartant) [inline src/internal/operators/pluck.ts:54]: I don't think the nullish coalescing operator (`??`) should be used here. It will convert values that are explicitly `null` to `undefined`. I think the optional chaining operator (`?.`) is sufficient.

Comment (anirudhvarma12) [reply src/internal/operators/pluck.ts]: Right, made the change.

Comment (cartant) [reply src/internal/operators/pluck.ts]: It does mean that if the value is `null`, the operator will emit `null` instead of `undefined`, but I'm okay with that. We'll see what the others think. LGTM.

**Comment by anirudhvarma12** [comment]
@cartant , is there a process to PR getting merged after approval? (Sorry if this is already documented somewhere, I could not find it)

**Comment by cartant** [comment]
PRs that update actual library code - i.e. not just tests or docs - need to be approved and merged by Ben.

**Comment by benlesh** [comment]
Merged also into 6.x, although with a slight alteration, as we don't compile with TS 3.9 there.
