### PR TITLE
fix(reduce): forward index to accumulator

### LINKED ISSUE #2290: Reduce() overload invoked with index=undefined
**RxJS version:**
5.0.3
**Code to reproduce:**
```
Rx.Observable.from([1,2,3,4,5])
  .reduce((acc,curr,index) => `${acc}\ncurr:${curr}@index(${index})`, '')
  .subscribe(console.log);
```

**Expected behavior:**

```
curr:1@index(0)
curr:2@index(1)
curr:3@index(2)
curr:4@index(3)
curr:5@index(4)"
```
**Actual behavior:**

```
curr:1@index(undefined)
curr:2@index(undefined)
curr:3@index(undefined)
curr:4@index(undefined)
curr:5@index(undefined)"
```

**Additional information:**

The `seed` argument does not matter, results are the same

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR updates `reduce` to forward index of an element as same as native reduce operator does. 

**Related issue (if exists):**
- closes #2290

### CODE REVIEW

File: src/operator/reduce.ts [hunk 1]
```diff
@@ -81,15 +81,20 @@ export class ReduceOperator<T, R> implements Operator<T, R> {
...
-              private accumulator: (acc: R, value: T) => R,
+              private accumulator: (acc: R, value: T, index?: number) => R,
               seed: R,
               private hasSeed: boolean) {
     super(destination);
     this.acc = seed;
+
+    if (!this.hasSeed) {
+      this.index++;
+    }
```
Comment (paulpdaniels) [inline src/operator/reduce.ts]: Why does index start at 1 if there is no seed?

Comment (kwonoj) [inline src/operator/reduce.ts]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

> currentIndex The index of the current element being processed in the array. Starts at index 0, if an initialValue is provided, and at index 1 otherwise.

I tried to follow same behavior to native reduce, where it says start from 0 if seed exists, 1 otherwise.

Comment (kwonoj) [inline src/operator/reduce.ts]: maybe I've read spec incorrectly?

Comment (paulpdaniels) [inline src/operator/reduce.ts]: @kwonoj Nope, you read it correctly. TIL.

Comment (crunchie84) [inline src/operator/reduce.ts]: Maybe worth documenting this behaviour in the RxJs documentation?
