### PR TITLE
fix(throttleTime): ensure the spacing between throttles is always at least the throttled amount

### LINKED ISSUE #2727: throttleTime(n, undefined, {leading: true, trailing: true}) ... double output
**RxJS version:** 6.5.1
**Code to reproduce (6.5.1):** https://stackblitz.com/edit/rxjs-tthiju
**Expected behavior:** One value initially, then defer next value for given `duration`
**Actual behavior:** One value initially, two values each `duration`
**Additional information:**

Test:

```javascript
import { interval } from 'rxjs'; 
import { throttleTime, take } from 'rxjs/operators';

interval(50).pipe(
  throttleTime(1234, undefined, {leading: true, trailing: true}),
  take(8),
).subscribe(x => console.log(x));

// actual output: 0----24-25----49-50----74-75----99|
// expected output: 0----24----49----74----99----124----149----174|
```

### LINKED ISSUE #3712: Invalid behavior of ThrottleTime operator
**RxJS version:**
5.5.8
6.1.0
rxjs-compat 6.1.0

**Code to reproduce:**

This is RxJs behavior

5.5.8
```js
const rx = require('rxjs');

const a = rx.Observable.timer(0, 700).throttleTime(1000, rx.Scheduler.async, { leading: true, trailing: true });
let lastDate = new Date();  
let d = a.subscribe(x => { 
    const now = new Date(); 
    console.log('\n' + x + ' ' + (now.getTime() - lastDate.getTime())); 
    lastDate = now; 
});
```

6.1.0
```js
const rx = require('rxjs');
require('rxjs/operators');
require('rxjs-compat/add/operator/throttleTime');

const a = rx.timer(0, 700).throttleTime(1000, rx.Scheduler.async, { leading: true, trailing: true });
let lastDate = new Date();  
let d = a.subscribe(x => { 
    const now = new Date(); 
    console.log('\n' + x + ' ' + (now.getTime() - lastDate.getTime())); 
    lastDate = now; 
});
```

**Expected behavior:**

This is underscore:

```js
const underscore = require('underscore');
const rx = require('rxjs');

let lastDate = new Date();  
d= rx.Observable.timer(0, 700).subscribe(underscore.throttle(x => { 
    const now = new Date(); 
    console.log('\n' + x + ' ' + (now.getTime() - lastDate.getTime())); 
    lastDate = now; 
}, 
1000, 
{ leading: true, trailing: true }))
```

```
11 1003
12 1002
/// missing 13, all intervals above 1 sec
14 1001
```

This is RxSwift behavior

```swift
var last = Date();
        _ = Observable<Int>.timer(0, period: 0.7, scheduler: MainScheduler.instance)
            .throttle(1.0, latest: true, scheduler: MainScheduler.instance)
            .subscribe({ next in
                let now = Date();
                print("\(next) \(now.timeIntervalSince(last))");
                last = now;
            })
```

```
next(11) 1.00001406669617
next(12) 1.00061988830566
// missing 13, all intervals above 1 sec
next(14) 1.00011909008026
```

**Actual behavior:**

```
11 1000
12 407 // <--- time interval less then 1 sec
13 1004 // <--- has 13
14 402
```

**Additional information:**

The operator `throttleTime` is not behaving as I would expect. If I set throttle interval to 1sec I should **never** receive elements under 1 sec.

### PR DESCRIPTION
**Pull request by benlesh**
Works to align the behavior with expectations set by lodash's throttle

- Updates tests
- Ensures trailing throttle will wait to notify and then complete
- Ensures that every time we emit a value a new throttle period starts

fixes #3712
related #4864
fixes #2727
closes #4727
related #4429

### CODE REVIEW

File: spec/operators/throttleTime-spec.ts [hunk 1]
```diff
@@ -1,200 +1,254 @@
...
-      const e1 =   hot('-a-xy-----b--x--cxx|');
-      const e1subs =   '^                  !';
-      const t =   time('----|               ');
-      const expected = '-----y--------x----(x|)';
+      rxTest.run(({ hot, time, expectObservable, expectSubscriptions }) => {
+        const e1 = hot('  -a-xy-----b--x--cxx|');
+        const e1subs = '  ^------------------!';
+        const t = time('   ----|              ');
+        //                 ----|---|----|---|---|
+        const expected = '-----y--------x---x---|';
```
Comment (cartant) [inline spec/operators/throttleTime-spec.ts:233]: question/nitpick: Should this really delay/throttle the completion of the source? This isn't the behaviour that I would have expected. Whatever the case, this test's description doesn't seem to describe what it's actually testing, IMO. If this is how it's supposed to behave, I think the description should explicitly state that complete notifications that are received whilst throttling will be delayed.

**Review by cartant — APPROVED** [review]
LGTM, but the behaviour surprised me a little. See comment below.

File: spec/operators/throttleTime-spec.ts (hunk 1 above)
Comment (benlesh) [reply spec/operators/throttleTime-spec.ts:233]: Ah... yeah, I think if it has to trailing value we should probably complete it.. I'll make that change and merge.
